eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8090
spring:
  application:
    name: server-feign
    thymeleaf.encoding: UTF-8
    thymeleaf.servlet.content-type: text/html

