server:
  port: 8087

spring:
  application:
    name: service-provider
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.121:3306/hdys?ServerTimeZone=HongKong&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/user
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

  redis:
    host: localhost
    port: 6379
    maxIdle: 300
    maxActive: 600
    maxWait: 1000
    testOnBorrow: true
    timeout: 1000

mybatis:
  mapper-locations: classpath:mapper/*.xml